version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: crm-dev-db
    environment:
      POSTGRES_DB: crm_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crm_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm-dev-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: crm-dev-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm-dev-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  crm-dev-network:
    driver: bridge