version: '3.8'

services:
  # Development Database
  db:
    image: postgres:15-alpine
    container_name: crm-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: crm_dev_db
      POSTGRES_USER: crm_dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_INITDB_ARGS: "--auth-host=trust"
    ports:
      - "5432:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_dev_user -d crm_dev_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm-dev-network

  # Development Redis
  redis:
    image: redis:7-alpine
    container_name: crm-dev-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - dev_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm-dev-network

  # Backend Development (with hot reload)
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
      target: development
    container_name: crm-dev-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://crm_dev_user:dev_password@db:5432/crm_dev_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-jwt-secret
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
      # AISensy WhatsApp API
      AISENSY_API_KEY: ${AISENSY_API_KEY}
      AISENSY_CAMPAIGN_NAME: ${AISENSY_CAMPAIGN_NAME:-CRM_Chat}
      AISENSY_WEBHOOK_SECRET: ${AISENSY_WEBHOOK_SECRET:-dev-webhook-secret}
    ports:
      - "3001:3001"
      - "3002:3002"
      - "9229:9229"  # Debug port
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
      - dev_backend_uploads:/app/uploads
    networks:
      - crm-dev-network

  # Frontend Development (with hot reload)
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
      target: development
    container_name: crm-dev-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3001
      NEXT_PUBLIC_WS_URL: ws://localhost:3001
      NEXT_PUBLIC_DEMO_MODE: "false"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - crm-dev-network

volumes:
  dev_postgres_data:
  dev_redis_data:
  dev_backend_uploads:

networks:
  crm-dev-network:
    driver: bridge