# fly.toml app configuration file generated for crm-mvp on 2025-07-27T18:01:59+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crm-backend-api'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[[mounts]]
  source = 'crm_data'
  destination = '/app/data'

# Backend API service - configured for extended uptime
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

# Machine configuration for extended uptime
[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
