# fly.toml app configuration file generated for crm-mvp on 2025-07-27T18:01:59+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crm-mvp'
primary_region = 'bom'

[build]
  dockerfile = 'infra/docker/Dockerfile.simple'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'crm_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[services]]
  protocol = 'tcp'
  internal_port = 5432

  [[services.ports]]
    port = 5432

[[services]]
  protocol = 'tcp'
  internal_port = 6379

  [[services.ports]]
    port = 6379

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
