version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    container_name: crm-test-db
    environment:
      POSTGRES_DB: crm_test_db
      POSTGRES_USER: crm_test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_test_user -d crm_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  test-redis:
    image: redis:7-alpine
    container_name: crm-test-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s