# Fly.io configuration for Redis
app = 'crm-mvp-redis'
primary_region = 'bom'

[build]
  image = 'redis:7-alpine'

[[mounts]]
  source = 'redis_data'
  destination = '/data'

[[services]]
  internal_port = 6379
  protocol = 'tcp'
  
  [[services.ports]]
    port = 6379

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1