name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: ${{ github.repository }}/frontend
  IMAGE_NAME_BACKEND: ${{ github.repository }}/backend

jobs:
  # Test and Quality Checks
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies  
      run: |
        # Clear caches for isolated-vm Node 24 compatibility
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install --verbose

    - name: Setup test database
      run: |
        cd apps/backend
        npm run db:migrate
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db

    - name: Run backend tests with coverage
      run: |
        cd apps/backend
        npm run test:ci
      env:
        NODE_ENV: test
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        REDIS_URL: redis://localhost:6379
        JWT_SECRET: test-jwt-secret
        SILENT_TESTS: true

    - name: Run frontend tests
      run: npm run test:frontend
      env:
        CI: true

    - name: Upload backend coverage
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: apps/backend/coverage
        retention-days: 7

    - name: Check backend coverage thresholds
      run: |
        cd apps/backend
        npm run coverage:check

    - name: Backend Type checking
      run: npm run typecheck:backend
      
    - name: Frontend Type checking  
      run: npm run typecheck:frontend

    - name: Backend Linting
      run: npm run lint:backend
        
    - name: Frontend Linting
      run: cd apps/frontend && npm run lint -- --max-warnings 0
        
    - name: Build check
      run: npm run build

  # Build and Push Docker Images
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    timeout-minutes: 10
    
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [frontend, backend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.service }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./apps/${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          CACHE_BUST=${{ github.sha }}

  # Deploy to Development
  deploy-dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Development
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.DEV_USERNAME }}
        key: ${{ secrets.DEV_SSH_KEY }}
        script: |
          cd /opt/crm-mvp
          git pull origin dev
          docker compose -f docker-compose.dev.yml down
          docker compose -f docker-compose.dev.yml pull
          docker compose -f docker-compose.dev.yml up -d
          docker system prune -f

  # Deploy to Production (disabled until production server is configured)
  deploy-prod:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: false # Disabled until production server credentials are configured
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Production
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          cd /opt/crm-mvp
          git pull origin main
          docker compose down
          docker compose pull
          docker compose up -d
          docker system prune -f

  # GitHub Pages deployment removed (private repository)
