# Simplified deployment workflow - skips tests, focuses on deployment
name: Deploy Only

on:
  push:
    branches: [ main ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      
      - name: Verify environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Current directory: $(pwd)"
          ls -la
      
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Check Fly.io authentication
        run: |
          if [ -z "$FLY_API_TOKEN" ]; then
            echo "FLY_API_TOKEN is not set!"
            exit 1
          fi
          flyctl auth whoami
      
      - name: Deploy to Fly.io
        run: |
          echo "Deploying to Fly.io..."
          flyctl deploy --remote-only --verbose
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}